### ISSUE TITLE
Report error message

### ISSUE THREAD

**Issue by gatunet** [kaiuri/nvim-juliana#12]
I'm on neovim 0.7.2, and I get this error message

<img width="1767" alt="Screen Shot 2022-07-19 at 18 40 28" src="https://user-images.githubusercontent.com/27605237/179853707-29806534-5628-4317-bf22-2c841712f4f8.png">

I have also pinned the plugin to the latest commit as of right now, *95fc05d53c7c304290f81638de19a73650e0fdaa*, sometimes it loads the background color, but still gives the error

**Comment by kaiuri** [comment]
Required version for using the colorscheme is `NVIM v0.8.0-dev`. The culprit is [this](https://github.com/neovim/neovim/issues/14090#issuecomment-1170955189) breaking change on neovim. As of now, v0.7 and v0.8 have different names for somethings related to highlights, _e.g._ `underdot` is now `underdotted`. That said, the colorscheme works fine on v0.8.0-dev.
