### ISSUE TITLE
How to disable keyword italic && make comment italic

### ISSUE THREAD

**Issue by Leiyi548** [kaiuri/nvim-juliana#16]
I think this colorscheme is good,but i have some issues.
I want to disable keyword italic and comment italic.But I don't see configuration in README.md.

**Comment by kaiuri** [comment]
Hi there, here both are not italic. Maybe there's some other plugin resetting those attributes? Could you send me a screenshot of what the theme looks like on your computer?

**Comment by kaiuri** [comment]
Thanks for the compliment.

Any italic, bold, etc, was taken from Sublime Mariana's highlights. There's no real pattern there besides `library` stuff being italicized. It shouldn't be hard to implement, though a PR is welcome since this isn't top priority for the plugin right now.

Top priority being fixing the highlight issue arisen from [19931](https://github.com/neovim/neovim/pull/19931) and the now missing `<filetype>TS` `hl-groups`.
