### ISSUE TITLE
Rust looks weird

### ISSUE THREAD

**Issue by polachok** [kaiuri/nvim-juliana#3]
I'm using nvim 0.7, not sure if it matters

Sublime on the left, nvim on the right:
<img width="986" alt="image" src="https://user-images.githubusercontent.com/94035/175824579-df126f30-a4b9-4537-a79a-0da548d1fd2a.png">

**Comment by kaiuri** [comment]
Sorry for that. I haven't written Rust code in while and didn't know about this quirk. Will fix it.

**Comment by kaiuri** [comment]
Fixed. Although, since `nvim-treesitter`'s default `rust` parser hl-groups lack some of SublimeText hl-groups, some differences over Generics' clauses remain. Meaning, there's some visual repetition which we can address if you'd be so kind as to provide some feedback/opinion on the color arrangement for `.rs` files.
